import Head from 'next/head'
import {fetchCoctails} from "../../lib/api/api";
import {Coctail} from "../../lib/model/coctail";

const CoctailPage = ({coctail}: { coctail: Coctail }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>

      <main>
        <h1>
          {coctail.name}
        </h1>

        <div>

          {coctail.ingredients.map(ingredient => (
            <a href="#" key={coctail.name}>
              <h2>{ingredient.name} ({ingredient.volume} ml)</h2>
            </a>
          ))}
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default CoctailPage

export async function getStaticPaths() {
  const coctails = await fetchCoctails();
  const paths = coctails.map(coctail => ({
    params: {coctail: coctail.name},
  }));
  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({params}: { params: any }) {
  const coctail = (await fetchCoctails()).filter(coctail => coctail.name === params.coctail)[0];
  return {
    props: {coctail}
  };
}