import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {fetchCoctails} from "../lib/api/api";
import {Coctail} from "../lib/model/coctail";
import Link from 'next/link';


const Home = ({ coctails }: { coctails: Coctail[]}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Coctails!</a>
        </h1>

        <div className={styles.grid}>

          {coctails.map(coctail => (
            <Link key={coctail.name} href={`/coctails/${encodeURIComponent(coctail.name)}`}>
              <a className={styles.card}>
                <h2>{coctail.name}</h2>
                <p>{coctail.ingredients.map(ingredient => `${ingredient.name} (${ingredient.volume} ml)`).join(', ')}</p>
              </a>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home

export async function getStaticProps() {
  const coctails = await fetchCoctails();
  return {
    props: { coctails }
  };
}